### ISSUE TITLE
Fail build step when assignment fails.

### ISSUE THREAD

**Issue by davidshorter** [neilpeterson/azure-blueprints-pipeline-tasks#50]
Be nice when the assignment fails if the build step would also fail.

Example YAML file.
![image](https://user-images.githubusercontent.com/13352856/68812607-5fe88d00-06d8-11ea-8d88-99c6bae6087d.png)

Results

![image](https://user-images.githubusercontent.com/13352856/68812523-2d3e9480-06d8-11ea-8b42-dd080e6d395b.png)

**Comment by davidshorter** [comment]
As another thought your step could write an output variable to let the consumer decide what action to take, e.g. apply `task.setvariable` and / or `task.logissue` as documented [here](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md) in this area of the [assignBlueprint](https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/blob/master/assignBlueprint/assignBlueprint.ps1#L105)

Awesome tool by the way :)

**Comment by neilpeterson** [comment]
@davidshorter nice catch, very valid. This should be an easy fix but will take a me a few days to find some code time.

I will get it taken care of - thanks for raising the issue.

**Comment by davidshorter** [comment]
@neilpeterson : This look ok ?
https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/pull/51

**Comment by neilpeterson** [comment]
@davidshorter  v 1.5.7 has been published with your contributions included. Thanks again.

https://marketplace.visualstudio.com/items?itemName=nepeters.azure-blueprints

**Comment by neilpeterson** [comment]
@davidshorter I've updated the code a bit for this one.

I've found that in order to fully fail the pipeline an error needs to be thrown. What i've done is to create a new task parameter `StopOnError`. When selected, on assignment failure, the pipeline will fail.

If `StopOnError` is not selected, on assignment failure, the failure will be logged and visible in results, however the pipeline itself will continue.

Here is the [updated code](https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/blob/master/assignBlueprint/assignBlueprint.ps1#L111), which has also been added to the [1.6.0 release](https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/releases/tag/1.6.0).

**Comment by neilpeterson** [comment]
Here is an example with `StopOnFailure: true`.

```
steps:
- task: nepeters.azure-blueprints.AssignBlueprint.AssignBlueprint@1
  displayName: 'Assign Azure Blueprint'
  inputs:
    azureSubscription: 'nepeters-internal'
    AssignmentName: 'prod-test-one'
    BlueprintName: 'prod-test-one'
    ParametersFile: 'assign/assign-blueprint.json'
    AlternateSubscription: true
    SubscriptionID: '00000000-0000-0000-0000-000000000000'
    Wait: true
    StopOnFailure: true
```

![image](https://user-images.githubusercontent.com/7844635/71550860-d262b300-298e-11ea-8918-76ffe9e552e2.png)

And with `StopOnFailure: false`.

```
steps:
- task: nepeters.azure-blueprints.AssignBlueprint.AssignBlueprint@1
  displayName: 'Assign Azure Blueprint'
  inputs:
    azureSubscription: 'nepeters-internal'
    AssignmentName: 'prod-test-one'
    BlueprintName: 'prod-test-one'
    ParametersFile: 'assign/assign-blueprint.json'
    AlternateSubscription: true
    SubscriptionID: '00000000-0000-0000-0000-000000000000'
    Wait: true
    StopOnFailure: false
```

![image](https://user-images.githubusercontent.com/7844635/71550852-be1eb600-298e-11ea-9c51-0337283deeba.png)
