### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by Lutando** [neilpeterson/azure-blueprints-pipeline-tasks#64]
Why is it that, in the docs [here](https://github.com/neilpeterson/azure-blueprints-pipeline-tasks/blob/master/docs/overview.md), that the task input key called `BlueprintPath` is valued with `create` in the documentation? 

```
steps:
- task: nepeters.azure-blueprints.CreateBlueprint.CreateBlueprint@1
  displayName: 'Create Azure Blueprint'
  inputs:
    azureSubscription: 'nepeters-devops-mgmt'
    BlueprintName: 'blueprints-demo'
    BlueprintPath: create
    PublishBlueprint: true
```

Mistake or is this referring to a create folder?
